.TH SHOWFOND 1 "23 October 2002"
.SH NAME
showfond \- display information about Macintosh font resources 
.SH SYNOPSIS
.B showfond
.BR  macfile ...
.SH DESCRIPTION
The program
.B showfond
dumps information about Macintosh font resources (FOND, NFNT, sfnt) 
found in the file(s) specified on the command line.
.SH AUTHOR
George Williams (gww@silcom.com).
.LP
Manual page by
Ziying Sherwin (sherwin@nlm.nih.gov) and
R.P.C Rodgers (rodgers@nlm.nih.gov),
Lister Hill National Center for Biomedical Communications,
U.S. National Library of Medicine.
.\" end of manual page
